Version Upgrade

diff --git a/0001-Fix-puppet-paths.patch b/0001-Fix-puppet-paths.patch
--- a/0001-Fix-puppet-paths.patch
+++ b/0001-Fix-puppet-paths.patch
@@ -1,13 +1,10 @@
 diff --git a/controller.sh b/controller.sh
-old mode 100644
-new mode 100755
-index a7a2be0..21d77f5
+index f1b5522..f54b5e1 100644
 --- a/controller.sh
 +++ b/controller.sh
-@@ -1,132 +1,6 @@
+@@ -1,132 +1,5 @@
  #!/bin/bash
-+basepath="$1"
- 
+-
 -set -ex
 -
 -################
@@ -108,11 +105,11 @@ index a7a2be0..21d77f5
 -esac
 -
 -# bash will eat your spaces, so let's array. see http://mywiki.wooledge.org/BashFAQ/050 for more fun.
--params=("--user" "puppet" "--group" "puppet" "--chdir" "$dir" "--realname" "puppetserver" "--operating-system" "$os" "--name" "puppetserver" "--package-version" "6.7.1" "--release" "1")
+-params=("--user" "puppet" "--group" "puppet" "--chdir" "$dir" "--realname" "puppetserver" "--operating-system" "$os" "--name" "puppetserver" "--package-version" "6.10.0" "--release" "1")
 -if [ -n "$os_version" ]; then params+=("--os-version" "$os_version"); fi
 -if [ -n "$os_dist" ]; then params+=("--dist" "$os_dist"); fi
 -
--params+=('--description' "$(printf "Puppet Labs puppetserver\nContains: Puppet Server (puppetlabs/puppetserver 6.7.1,org.clojure/clojure 1.10.1,org.bouncycastle/bcpkix-jdk15on 1.60,puppetlabs/puppetserver 6.7.1,puppetlabs/trapperkeeper-webserver-jetty9 4.0.1)")")
+-params+=('--description' "$(printf "Puppet Labs puppetserver\nContains: Puppet Server (puppetlabs/puppetserver 6.10.0,org.clojure/clojure 1.10.1,org.bouncycastle/bcpkix-jdk15on 1.60,puppetlabs/jruby-utils 3.1.1,puppetlabs/puppetserver 6.10.0,puppetlabs/trapperkeeper-webserver-jetty9 4.0.3)")")
 -
 -
 -
@@ -138,11 +135,12 @@ index a7a2be0..21d77f5
 -
 -
 -ruby $PWD/ext/fpm.rb "${params[@]}"
++basepath="$1"
 +mkdir -p $basepath
 +DESTDIR="$basepath" bash install.sh install_redhat
 +DESTDIR="$basepath" bash install.sh systemd_redhat
 diff --git a/ext/bin/puppetserver b/ext/bin/puppetserver
-index 3cb051e..0204004 100644
+index 17b9e38..f8e5dab 100644
 --- a/ext/bin/puppetserver
 +++ b/ext/bin/puppetserver
 @@ -13,7 +13,7 @@ elif [ `uname` == "OpenBSD" ] ; then
@@ -155,7 +153,7 @@ index 3cb051e..0204004 100644
  else
      echo "You seem to be missing some important configuration files; could not find /etc/default/puppetserver or /etc/sysconfig/puppetserver" >&2
 diff --git a/ext/build-scripts/install-vendored-gems.sh b/ext/build-scripts/install-vendored-gems.sh
-index b009a1c..2bb0c92 100644
+index 84d1892..9f7d0af 100644
 --- a/ext/build-scripts/install-vendored-gems.sh
 +++ b/ext/build-scripts/install-vendored-gems.sh
 @@ -14,7 +14,7 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
@@ -239,30 +237,31 @@ index 4c89c6b..ae02ce1 100644
 -CLASSPATH="${CLASSPATH}:/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/facter.jar:/opt/puppetlabs/server/data/puppetserver/jars/*"
 +CLASSPATH="${CLASSPATH}:/usr/share/puppetlabs/puppet/lib/ruby/vendor_ruby/facter.jar:/usr/share/puppetlabs/server/data/puppetserver/jars/*"
 diff --git a/ext/config/conf.d/puppetserver.conf b/ext/config/conf.d/puppetserver.conf
-index 7253338..2ed5f04 100644
+index 7253338..d6183a3 100644
 --- a/ext/config/conf.d/puppetserver.conf
 +++ b/ext/config/conf.d/puppetserver.conf
-@@ -2,16 +2,16 @@
+@@ -2,16 +2,17 @@
  jruby-puppet: {
      # Where the puppet-agent dependency places puppet, facter, etc...
      # Puppet server expects to load Puppet from this location
 -    ruby-load-path: [/opt/puppetlabs/puppet/lib/ruby/vendor_ruby]
 +    ruby-load-path: [/usr/share/puppetlabs/puppet/lib/ruby/vendor_ruby, "/usr/share/gems/gems/puppetserver-ca-1.5.0/lib", "/usr/share/ruby/vendor_ruby"]
++
  
      # This setting determines where JRuby will install gems.  It is used for loading gems,
      # and also by the `puppetserver gem` command line tool.
 -    gem-home: /opt/puppetlabs/server/data/puppetserver/jruby-gems
-+    gem-home: /usr/share/puppetlabs/server/data/puppetserver/jruby-gems
++    gem-path: [${jruby-puppet.gem-home}, "/usr/share/puppetlabs/server/data/puppetserver/vendored-jruby-gems", "/usr/share/puppetlabs/puppet/lib/ruby/vendor_gems", "/usr/share/gems"]
  
      # This setting defines the complete "GEM_PATH" for jruby.  If set, it should include
      # the gem-home directory as well as any other directories that gems can be loaded
      # from (including the vendored gems directory for gems that ship with puppetserver)
 -    gem-path: [${jruby-puppet.gem-home}, "/opt/puppetlabs/server/data/puppetserver/vendored-jruby-gems", "/opt/puppetlabs/puppet/lib/ruby/vendor_gems"]
-+    gem-path: [${jruby-puppet.gem-home}, "/usr/share/puppetlabs/server/data/puppetserver/vendored-jruby-gems", "/usr/share/puppetlabs/puppet/lib/ruby/vendor_gems", "/usr/share/gems"]
++    gem-path: [${jruby-puppet.gem-home}, "/usr/share/puppetlabs/server/data/puppetserver/vendored-jruby-gems", "/usr/share/puppetlabs/puppet/lib/ruby/vendor_gems"]
  
      # PLEASE NOTE: Use caution when modifying the below settings. Modifying
      # these settings will change the value of the corresponding Puppet settings
-@@ -33,8 +33,8 @@ jruby-puppet: {
+@@ -33,8 +34,8 @@ jruby-puppet: {
      master-code-dir: /etc/puppetlabs/code
  
      # (optional) path to puppet var dir; if not specified, will use
@@ -273,6 +272,76 @@ index 7253338..2ed5f04 100644
  
      # (optional) path to puppet run dir; if not specified, will use
      # /var/run/puppetlabs/puppetserver
+diff --git a/ext/debian/postinst b/ext/debian/postinst
+index d5496f4..5bba10b 100644
+--- a/ext/debian/postinst
++++ b/ext/debian/postinst
+@@ -1,10 +1,10 @@
+ #!/bin/sh
+ 
+-/opt/puppetlabs/server/apps/puppetserver/scripts/install.sh postinst_deb
++/usr/share/puppetlabs/server/apps/puppetserver/scripts/install.sh postinst_deb
+ 
+ # Set some configuration from the project on install
+ if [ -z "$2" ]; then
+-  /opt/puppetlabs/server/apps/puppetserver/scripts/install.sh postinst_deb_install
++  /usr/share/puppetlabs/server/apps/puppetserver/scripts/install.sh postinst_deb_install
+ fi
+ 
+ # On upgrade, we should restart the service if it's running
+diff --git a/ext/debian/preinst b/ext/debian/preinst
+index ec6f91d..62de027 100644
+--- a/ext/debian/preinst
++++ b/ext/debian/preinst
+@@ -13,11 +13,11 @@ if [ "$1" = install ] || [ "$1" = upgrade ]; then
+     # Add puppet user
+     if getent passwd puppet > /dev/null; then
+       usermod --gid puppet \
+-        --home /opt/puppetlabs/server/data/puppetserver \
++        --home /usr/share/puppetlabs/server/data/puppetserver \
+         --comment "puppetserver daemon" puppet || :
+     else
+       useradd -r --gid puppet \
+-        --home /opt/puppetlabs/server/data/puppetserver  --shell $(which nologin) \
++        --home /usr/share/puppetlabs/server/data/puppetserver  --shell $(which nologin) \
+         --comment "puppetserver daemon"  puppet || :
+     fi
+ 
+diff --git a/ext/debian/puppetserver.default_file b/ext/debian/puppetserver.default_file
+index dc78c98..258aaa5 100644
+--- a/ext/debian/puppetserver.default_file
++++ b/ext/debian/puppetserver.default_file
+@@ -17,11 +17,11 @@ TK_ARGS=""
+ # These normally shouldn't need to be edited if using OS packages
+ USER="puppet"
+ GROUP="puppet"
+-INSTALL_DIR="/opt/puppetlabs/server/apps/puppetserver"
++INSTALL_DIR="/usr/share/puppetlabs/server/apps/puppetserver"
+ CONFIG="/etc/puppetlabs/puppetserver/conf.d"
+ 
+ # Bootstrap path
+-BOOTSTRAP_CONFIG="/etc/puppetlabs/puppetserver/services.d/,/opt/puppetlabs/server/apps/puppetserver/config/services.d/"
++BOOTSTRAP_CONFIG="/etc/puppetlabs/puppetserver/services.d/,/usr/share/puppetlabs/server/apps/puppetserver/config/services.d/"
+ 
+ # SERVICE_STOP_RETRIES can be set here to alter the default stop timeout in
+ # seconds.  For systemd, the shorter of this setting or 'TimeoutStopSec' in
+diff --git a/ext/debian/puppetserver.service_file b/ext/debian/puppetserver.service_file
+index 9e4802c..a9fb3dc 100644
+--- a/ext/debian/puppetserver.service_file
++++ b/ext/debian/puppetserver.service_file
+@@ -34,9 +34,9 @@ TasksMax=4915
+ UMask=027
+ 
+ 
+-ExecReload=/opt/puppetlabs/server/apps/puppetserver/bin/puppetserver reload
+-ExecStart=/opt/puppetlabs/server/apps/puppetserver/bin/puppetserver start
+-ExecStop=/opt/puppetlabs/server/apps/puppetserver/bin/puppetserver stop
++ExecReload=/usr/share/puppetlabs/server/apps/puppetserver/bin/puppetserver reload
++ExecStart=/usr/share/puppetlabs/server/apps/puppetserver/bin/puppetserver start
++ExecStop=/usr/share/puppetlabs/server/apps/puppetserver/bin/puppetserver stop
+ 
+ KillMode=process
+ 
 diff --git a/ext/default b/ext/default
 index dc78c98..258aaa5 100644
 --- a/ext/default
@@ -292,7 +361,7 @@ index dc78c98..258aaa5 100644
  # SERVICE_STOP_RETRIES can be set here to alter the default stop timeout in
  # seconds.  For systemd, the shorter of this setting or 'TimeoutStopSec' in
 diff --git a/ext/fpm.rb b/ext/fpm.rb
-index f903a1d..d76efe1 100644
+index f903a1d..eb2fe1e 100644
 --- a/ext/fpm.rb
 +++ b/ext/fpm.rb
 @@ -137,9 +137,9 @@ if options.sources.empty?
@@ -300,21 +369,19 @@ index f903a1d..d76efe1 100644
                      when :fedora, :sles, :el, :redhatfips
                        if options.operating_system == :el && options.os_version < 7 || options.operating_system == :sles && options.os_version < 12 #sysv rpm platforms
 -                        ['etc', 'opt', 'var']
-+                        ['etc', 'usr/local', 'var']
++                        ['etc', 'usr/share', 'var']
                        else
 -                        ['etc', 'opt', 'usr', 'var']
-+                        ['etc', 'usr', 'var']
++                        ['etc', 'usr/share', 'usr', 'var']
                        end
                      when :debian, :ubuntu
                        if options.dist == 'trusty' #trusty is the only sysv deb we build for right now
-@@ -158,9 +158,9 @@ shared_opts = Array('')
- termini_opts = Array('')
+@@ -159,8 +159,8 @@ termini_opts = Array('')
  
  options.app_logdir = "/var/log/puppetlabs/#{options.realname}"
--options.app_rundir = "/var/run/puppetlabs/#{options.realname}"
+ options.app_rundir = "/var/run/puppetlabs/#{options.realname}"
 -options.app_prefix = "/opt/puppetlabs/server/apps/#{options.realname}"
 -options.app_data = "/opt/puppetlabs/server/data/#{options.realname}"
-+options.app_rundir = "/run/puppetlabs/#{options.realname}"
 +options.app_prefix = "/usr/share/puppetlabs/server/apps/#{options.realname}"
 +options.app_data = "/usr/share/puppetlabs/server/data/#{options.realname}"
  
@@ -411,7 +478,7 @@ index cc1d475..2204fed 100644
  KillMode=process
  
 diff --git a/install.sh b/install.sh
-index f379f90..9d82bfd 100644
+index eb26171..406508d 100644
 --- a/install.sh
 +++ b/install.sh
 @@ -22,14 +22,14 @@ confdir=${confdir:=/etc}
@@ -462,11 +529,11 @@ index f379f90..9d82bfd 100644
 -    usermod --home /opt/puppetlabs/server/data/puppetserver puppet
 -    install --directory --owner=puppet --group=puppet --mode=775 /opt/puppetlabs/server/data
 +    install --owner=puppet --group=puppet -d /usr/share/puppetlabs/server/data/puppetserver/jruby-gems
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master vardir  /usr/share/puppetlabs/server/data/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master logdir  /var/log/puppetlabs/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master rundir  /var/run/puppetlabs/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master pidfile /var/run/puppetlabs/puppetserver/puppetserver.pid
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master codedir /etc/puppetlabs/code
++    /usr/bin/puppet config set --section master vardir  /usr/share/puppetlabs/server/data/puppetserver
++    /usr/bin/puppet config set --section master logdir  /var/log/puppetlabs/puppetserver
++    /usr/bin/puppet config set --section master rundir  /var/run/puppetlabs/puppetserver
++    /usr/bin/puppet config set --section master pidfile /var/run/puppetlabs/puppetserver/puppetserver.pid
++    /usr/bin/puppet config set --section master codedir /etc/puppetlabs/code
 +    usermod --home /usr/share/puppetlabs/server/data/puppetserver puppet
 +    install --directory --owner=puppet --group=puppet --mode=775 /usr/share/puppetlabs/server/data
      install --directory /etc/puppetlabs/puppet/ssl
@@ -485,11 +552,11 @@ index f379f90..9d82bfd 100644
 -    usermod --home /opt/puppetlabs/server/data/puppetserver puppet
 -    install --directory --owner=puppet --group=puppet --mode=775 /opt/puppetlabs/server/data
 +    install --owner=puppet --group=puppet -d /usr/share/puppetlabs/server/data/puppetserver/jruby-gems
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master vardir  /usr/share/puppetlabs/server/data/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master logdir  /var/log/puppetlabs/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master rundir  /var/run/puppetlabs/puppetserver
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master pidfile /var/run/puppetlabs/puppetserver/puppetserver.pid
-+    /usr/share/puppetlabs/puppet/bin/puppet config set --section master codedir /etc/puppetlabs/code
++    /usr/bin/puppet config set --section master vardir  /usr/share/puppetlabs/server/data/puppetserver
++    /usr/bin/puppet config set --section master logdir  /var/log/puppetlabs/puppetserver
++    /usr/bin/puppet config set --section master rundir  /var/run/puppetlabs/puppetserver
++    /usr/bin/puppet config set --section master pidfile /var/run/puppetlabs/puppetserver/puppetserver.pid
++    /usr/bin/puppet config set --section master codedir /etc/puppetlabs/code
 +    usermod --home /usr/share/puppetlabs/server/data/puppetserver puppet
 +    install --directory --owner=puppet --group=puppet --mode=775 /usr/share/puppetlabs/server/data
      install --directory /etc/puppetlabs/puppet/ssl
